export enum ENUM_SETTING_GROUP {
  SYSTEM = 'SYSTEM',
  APP_VERSION = 'APP_VERSION',
  OPEN_WORK = 'OPEN_WORK',
}

export enum ENUM_SETTING_TYPE {
  BOOLEAN = 'BOOLEAN',
  YESNO = 'YESNO',
  ONOFF = 'ONOFF',
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  ARRAY_OF_STRING = 'ARRAY_OF_STRING',
  ARRAY_OF_NUMBER = 'ARRAY_OF_NUMBER',
}
