export const RESPONSE_DTO_CONSTRUCTOR_METADATA = 'nest_web_module:response_dto_constructor'
export const RESPONSE_DTO_OPTIONS_METADATA = 'nest_web_module:response_dto_options'
export const RESPONSE_FILE_TYPE_METADATA = 'nest_web_module:response_file_type'
export const RESPONSE_FILE_EXPORT_METADATA = 'nest_web_module:response_file_export'
export const RESPONSE_FILE_DISPOSITION_METADATA = 'nest_web_module:response_file_disposition'
export const RESPONSE_DEBUG_LOGGER_METADATA = 'nest_web_module:response_debug_logger'
