import { ENUM_FILE_MIME, FILE_SIZE_IN_LARGE_BYTES } from 'lib/nest-core'

export const MEMBER_UPLOAD_IMAGE_PATH = `public/uploads/images/members`
export const MEMBER_UPLOAD_TASK_SIZE = FILE_SIZE_IN_LARGE_BYTES
export const MEMBER_UPLOAD_AVATAR_MIME = [
  ENUM_FILE_MIME.JPEG,
  ENUM_FILE_MIME.JPG,
  ENUM_FILE_MIME.PNG,
]
export const MEMBER_UPLOAD_TASK_MIME = [
  ENUM_FILE_MIME.JPEG,
  ENUM_FILE_MIME.JPG,
  ENUM_FILE_MIME.PNG,
  ENUM_FILE_MIME.MP4,
  ENUM_FILE_MIME.MPEG,
  ENUM_FILE_MIME.MOV,
]

export const MEMBER_QUEUE_AUTH = 'MEMBER_QUEUE_AUTH'
export const MEMBER_QUEUE_SEND_REQUEST_OTP = 'MEMBER_QUEUE_SEND_REQUEST_OTP'
export const MEMBER_QUEUE_SEND_RESET_PASSWORD = 'MEMBER_QUEUE_SEND_RESET_PASSWORD'

export const MEMBER_NUMBER_LENGTH = Number.parseInt(process.env.AUTH_MEMBER_NUMBER_LENGTH || '4')
