export enum Subject {
  DASHBOARD = 'DASHBOARD',
  USER = 'USER',
  MEMBER = 'MEMBER',
  TIER_HISTORY = 'TIER_HISTORY',
  POINT_HISTORY = 'POINT_HISTORY',
  PRODUCT_HISTORY = 'PRODUCT_HISTORY',
  PRODUCT = 'PRODUCT',
  PRODUCT_BRAND = 'PRODUCT_BRAND',
  PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
  PRODUCT_REVIEW = 'PRODUCT_REVIEW',
  ORDER = 'ORDER',
  INVOICE = 'INVOICE',
  NOTIFICATION = 'NOTIFICATION',
  NOTIFICATION_HISTORY = 'NOTIFICATION_HISTORY',
  PUSH = 'PUSH',
  PUSH_GROUP = 'PUSH_GROUP',
  ROLE = 'ROLE',
  TIER = 'TIER',
  FACT = 'FACT',
  COUNTRY = 'COUNTRY',
  DISTRICT = 'DISTRICT',
  MEDIA = 'MEDIA',
  API_KEY = 'API_KEY',
  APP_VERSION = 'APP_VERSION',
}

export enum Action {
  READ = 'read',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
}

export const SUBJECT_TO_PATH: Partial<Record<Subject, string>> = {
  [Subject.DASHBOARD]: '/dashboard',
  [Subject.USER]: '/users',
  [Subject.MEMBER]: '/members',
  [Subject.TIER_HISTORY]: '/member-tiers',
  [Subject.POINT_HISTORY]: '/member-points',
  [Subject.PRODUCT_HISTORY]: '/member-redemptions',
  [Subject.NOTIFICATION_HISTORY]: '/member-notifications',
  [Subject.PRODUCT]: '/products',
  [Subject.PRODUCT_BRAND]: '/product-brands',
  [Subject.PRODUCT_CATEGORY]: '/product-categories',
  [Subject.PRODUCT_REVIEW]: '/product-reviews',
  [Subject.ORDER]: '/orders',
  [Subject.INVOICE]: '/invoices',
  [Subject.NOTIFICATION]: '/notifications',
  [Subject.PUSH]: '/pushes',
  [Subject.PUSH_GROUP]: '/push-groups',
  [Subject.ROLE]: '/roles',
  [Subject.TIER]: '/tiers',
  [Subject.FACT]: '/facts',
  [Subject.COUNTRY]: '/countries',
  [Subject.DISTRICT]: '/districts',
  [Subject.MEDIA]: '/media',
  [Subject.API_KEY]: '/api-keys',
  [Subject.APP_VERSION]: '/app-versions',
}
