export enum ENUM_AUTH_SIGN_UP_FROM {
  SEED = 'SEED',
  MIGRATE = 'MIGRATE',
  CMS = 'CMS',
  APP = 'APP',
  WEB = 'WEB',
}

export enum ENUM_AUTH_LOGIN_WITH {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
}

export enum ENUM_AUTH_LOGIN_FROM {
  CMS = 'CMS',
  APP = 'APP',
  WEB = 'WEB',
}

export enum ENUM_AUTH_LOGIN_TYPE {
  CREDENTIAL = 'CREDENTIAL',
  SOCIAL_GOOGLE = 'SOCIAL_GOOGLE',
  SOCIAL_APPLE = 'SOCIAL_APPLE',
  WHATSAPP = 'WHATSAPP',
}

export enum ENUM_AUTH_SCOPE_TYPE {
  USER = 'USER',
  MEMBER = 'MEMBER',
}
