export enum ENUM_AUTH_SIGN_UP_FROM {
  SEED = 'SEED',
  MIGRATE = 'MIGRATE',
  CMS = 'CMS',
  APP = 'APP',
  WEB = 'WEB',
}

export enum ENUM_AUTH_LOGIN_WITH {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
}

export enum ENUM_AUTH_LOGIN_FROM {
  CMS = 'CMS',
  APP = 'APP',
  WEB = 'WEB',
}

export enum ENUM_AUTH_LOGIN_TYPE {
  CREDENTIAL = 'CREDENTIAL',
  SOCIAL_GOOGLE = 'SOCIAL_GOOGLE',
  SOCIAL_APPLE = 'SOCIAL_APPLE',
  WHATSAPP = 'WHATSAPP',
}

export enum ENUM_AUTH_SCOPE_TYPE {
  USER = 'USER',
  MEMBER = 'MEMBER',
}

export enum ENUM_AUTH_ABILITY_ACTION {
  // MANAGE = 'manage',
  READ = 'read',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  EXPORT = 'export',
  IMPORT = 'import',
}

export enum ENUM_AUTH_ABILITY_ACTION_MAPPER {
  READ = 1 << 0,
  CREATE = 1 << 1,
  UPDATE = 1 << 2,
  DELETE = 1 << 3,
  IMPORT = 1 << 4,
  EXPORT = 1 << 5,
}

export enum ENUM_AUTH_ABILITY_SUBJECT {
  DASHBOARD = 'DASHBOARD',
  SETTING = 'SETTING',
  MEDIA = 'MEDIA',
  API_KEY = 'API_KEY',
  APP_VERSION = 'APP_VERSION',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  USER = 'USER',
  FACT = 'FACT',
  COUNTRY = 'COUNTRY',
  DISTRICT = 'DISTRICT',
  MEMBER = 'MEMBER',
  TIER_HISTORY = 'TIER_HISTORY',
  POINT_HISTORY = 'POINT_HISTORY',
  NOTIFICATION_HISTORY = 'NOTIFICATION_HISTORY',
  PRODUCT = 'PRODUCT',
  PRODUCT_BRAND = 'PRODUCT_BRAND',
  PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
  PRODUCT_REVIEW = 'PRODUCT_REVIEW',
  PRODUCT_HISTORY = 'PRODUCT_HISTORY',
  CART = 'CART',
  INVOICE = 'INVOICE',
  ORDER = 'ORDER',
  TIER = 'TIER',
  NOTIFICATION = 'NOTIFICATION',
  PUSH = 'PUSH',
  PUSH_GROUP = 'PUSH_GROUP',
}

export enum ENUM_AUTH_ABILITY_CONTEXT {
  DASHBOARD = 'DASHBOARD',
  SETTING_MANAGEMENT = 'SETTING_MANAGEMENT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  MEMBER_MANAGEMENT = 'MEMBER_MANAGEMENT',
  INVENTORY_MANAGEMENT = 'INVENTORY_MANAGEMENT',
  SALE_MANAGEMENT = 'SALE_MANAGEMENT',
  NOTIFICATION_MANAGEMENT = 'NOTIFICATION_MANAGEMENT',
}
