/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum EnumDateFormat {
  DB_DATE = 'yyyy-MM-dd',
  DB_TIME = 'yyyy-MM-dd HH:mm:ssZ',
  DATE_TIME = 'dd/MM/yyyy HH:mm:ss',
  DATE_TIME_SHORT = 'dd/MM/yyyy HH:mm',
  DATE = 'dd/MM/yyyy',
  TIME = 'HH:mm:ss',
  HUMAN_DATE = 'dd-MM-yyyy',
  FRIENDLY_DATE = 'dd MMM yyyy',
  FRIENDLY_DATE_TIME = 'dd MMM yyyy HH:mm:ss',
  FRIENDLY_DATE_WITH_DAY = 'cccc, dd MMM yyyy',
  FRIENDLY_DATE_TIME_WITH_DAY = 'cccc, dd MMM yyyy HH:mm:ss',
  DATE_REFERENCE = 'yyyyMMdd',
  YEAR_MONTH_REFERENCE = 'yyyyMM',
  YEAR_MONTH = 'yyyy-MM',
  MONTH_DATE = 'MM-dd',
  ONLY_YEAR = 'yyyy',
  ONLY_MONTH = 'MM',
  ONLY_DATE = 'dd',
  ISO_DATE = "yyyy-MM-dd'T'HH:mm:ssZ",
  DAY_LONG = 'cccc',
  DAY_SHORT = 'ccc',
  DURATION_LONG = 'HH:mm:ss',
  DURATION_SHORT = 'HH:mm',
  HOUR_LONG = 'HH',
  HOUR_SHORT = 'H',
  MINUTE_LONG = 'mm',
  MINUTE_SHORT = 'm',
  SECOND_LONG = 'ss',
  SECOND_SHORT = 's',
  TIMEZONE = 'Z',
}
