name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    environment: staging
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pwd
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file for tests
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive

      - name: Run Tests
        run: yarn test
        env:
          DATABASE_DEBUG: false
          DATABASE_LAZY: true
          DATABASE_MIGRATE: true
          DATABASE_URL: mysql://test_user:test_pwd@localhost:3306/app_test
