name: Auto Deploy NestJS to VPS

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deploy stage (staging or production)'
        required: true
        default: 'staging'

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /app

            # Pull latest image from GHCR for stage
            docker pull ghcr.io/${{ github.repository }}:${STAGE}

            STAGE=$(STAGE) docker compose -f ./deploy/docker-compose.yml up -d --force-recreate
