name: Deploy to Staging
on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and Package Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging -f deploy/Dockerfile . --build-arg APP_ENV=staging
          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging | gzip > app.tgz

      # - name: Configure SSH Key
      #   uses: webfactory/ssh-agent@v0.4.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'docker-compose.yml,app.tgz'
          target: /app
          timeout: 10m

      - name: Connect to Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app
            tar -xzf app.tgz
            docker load -i app.tgz
            rm app.tgz
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            TAG=staging docker compose -f ./deploy/docker-compose.yml up -d --force-recreate