name: Auto Deploy NestJS to VPS

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deploy stage (staging or production)'
        required: true
        default: 'staging'

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /app

            make deploy STAGE=${{ github.event.inputs.stage }}
