name: Linter
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deploy stage (staging or production)'
        required: true
        default: 'staging'

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run ESLint & Prettier
        run: yarn lint

  lint-commit-message:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint commit messages with commitlint
        run: npx commitlint --from=HEAD~10 --to=HEAD --verbose
